# ansible/site.yml

---
- hosts: rails
  remote_user: root
  become: true

  tasks:

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: true
        update_cache: true

    - import_tasks: tasks/users.yml

    - import_tasks: tasks/common.yml

    - import_tasks: tasks/ruby.yml

    - import_tasks: tasks/node.yml

    - import_tasks: tasks/imagemagick.yml

    - import_tasks: tasks/nginx.yml

    - import_tasks: tasks/redis.yml

    - import_tasks: tasks/postgres.yml

    - import_tasks: tasks/fail2ban.yml

    - import_tasks: tasks/ufw.yml # NOTE: not implemented

    - import_tasks: tasks/rails.yml
